# Generated by Django 5.1.5 on 2025-01-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('related_date', '-created_at')},
        ),
    ]
