# Generated by Django 5.1.5 on 2025-01-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_remove_note_related_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('-created_at',)},
        ),
    ]
